# Generated by Django 4.0.1 on 2022-03-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
