# Generated by Django 4.0.1 on 2022-03-21 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0002_alter_covid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
