# Generated by Django 4.0.1 on 2022-03-21 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covid', '0003_alter_covid_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='covid',
            name='date',
            field=models.CharField(max_length=120),
        ),
    ]
